version: '3.7'
services:
  api:
    image: covid-19-stats:1.0
    ports:
        - "3000:3000"
    expose:
        - "3000"
    environment:
      NODE_ENV: production
      db_connection_string: mongodb://db:27017/covid19
    depends_on:
        - db
    networks:
        - app-network
    restart: on-failure

  db:
    image: mongo:4.2
    ports:
        - "27017:27017"
    networks:
        - app-network
    restart: on-failure

networks:
    app-network:
        driver: bridge