openapi: 3.0.0
info:
  version: 1.0.0
  title: COVID-19 stats server
servers:
  - url: 'http://localhost:3000/api'
  - url: 'https://covid-19.com/api'
paths:
  /cases:
    get:
      summary: 'Returns total count for all types of cases'
      operationId: getCases
      tags:
        - cases
      parameters:
        - name: country
          in: query
          description: Country name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'Number of total cases grouped by case types'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cases'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /cases/country:
    get:
      summary: 'Returns total count for given case type with country'
      operationId: getCasesByCountry
      tags:
        - country
      parameters:
        - name: type
          in: query
          description: Case type
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'List of countries with given case types'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /cases/state:
    get:
      summary: 'Returns total count for given case type with state'
      operationId: getCasesByState
      tags:
        - state
      parameters:
        - name: type
          in: query
          description: Case type
          required: true
          schema:
            type: string
        - name: country
          in: query
          description: Country name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'List of state with given case types'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/State'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Cases:
      type: object
      required:
        - confirmed
        - deaths
        - recovered
      properties:
        confirmed:
          type: integer
          format: int64
        deaths:
          type: integer
          format: int64
        recovered:
          type: integer
          format: int64

    Country:
      type: array
      items:
        type: object
        required:
          - country
          - count
        properties:
          country:
            type: string
          count:
            type: integer
            format: int64
    State:
      type: array
      items:
        type: object
        required:
          - country
          - state
          - count
        properties:
          country:
            type: string
          state:
            type: string
          count:
            type: integer
            format: int64
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string